version: '3.8'

services:
  backend:
    build:
      context: ../asosFABE  # Updated path to your FastAPI app directory
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ../asosFABE:/app

  frontend:
    build:
      context: ../ASOS_FE/asos-fe
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "4200:4200"
    networks:
      - app-network
    volumes:
      - ../ASOS_FE/asos-fe:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:


networks:
  app-network:
    driver: bridge
